# Generated by Django 5.0.6 on 2024-05-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petrecord", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="id",
        ),
        migrations.AlterField(
            model_name="owner",
            name="nick",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="owner",
            name="password",
            field=models.CharField(max_length=50),
        ),
    ]
