# Generated by Django 5.0.6 on 2024-05-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petrecord", "0002_remove_owner_id_alter_owner_nick_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="owner_picture",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
