# Generated by Django 5.0.6 on 2024-05-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petrecord", "0004_alter_owner_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("dob", models.DateField()),
                ("dod", models.DateField()),
                ("category", models.CharField(max_length=20)),
                ("breed", models.CharField(max_length=20)),
            ],
        ),
    ]
