# Generated by Django 5.0.6 on 2024-05-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petrecord", "0005_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="pet",
            name="dod",
            field=models.DateField(blank=True),
        ),
    ]
