# Generated by Django 5.0.6 on 2024-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petrecord", "0006_alter_pet_breed_alter_pet_dod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="dod",
            field=models.DateField(default=None),
        ),
    ]
