# Generated by Django 5.0.6 on 2024-05-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petrecord", "0010_alter_pet_dod"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner_Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_nick",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petrecord.owner",
                    ),
                ),
                (
                    "pet_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petrecord.pet"
                    ),
                ),
            ],
        ),
    ]
