# Generated by Django 5.0.6 on 2024-05-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petrecord", "0011_owner_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="owner_picture",
            field=models.CharField(
                blank=True,
                default="https://res.cloudinary.com/dby1mkv4k/image/upload/v1716740486/zghvwtfpkpsm1dn6srpe.png",
                max_length=255,
            ),
        ),
    ]
