# Generated by Django 5.0.6 on 2024-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrecord', '0012_alter_owner_owner_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='dod',
        ),
        migrations.AddField(
            model_name='owner',
            name='mail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='chip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_picture',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/dby1mkv4k/image/upload/v1716740486/zghvwtfpkpsm1dn6srpe.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
