# Generated by Django 5.0.6 on 2024-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrecord', '0013_remove_pet_dod_owner_mail_pet_chip_pet_pet_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_picture',
            field=models.CharField(blank=True, default='http://res.cloudinary.com/dby1mkv4k/image/upload/v1716996247/hd1kh1fqqzijxrsf1gsi.png', max_length=255),
        ),
    ]
